"use strict";var geo_variable={"contact":{"address":"Lorem ipsum dolor sit amet, consectetur adipiscing elit","marker":"/url image"},"i18n":{"VIEW":"View","VIEWS":"Views","validate":{"form":{"SUBMIT":"Submit","SENDING":"Sending..."},"name":{"REQUIRED":"Please enter your name","MINLENGTH":"At least {0} characters required"},"email":{"REQUIRED":"Please enter your email","EMAIL":"Please enter a valid email"},"url":{"REQUIRED":"Please enter your url","URL":"Please enter a valid url"},"message":{"REQUIRED":"Please enter a message","MINLENGTH":"At least {0} characters required"}}}};var map;Modernizr.load([{load:geo_params.theme_uri+'js/superfish.js',complete:function(){jQuery('#main-menu').superfish({delay:400,speed:'fast',cssArrows:false});}}]);Modernizr.load([{load:geo_params.theme_uri+'js/jquery.navgoco.js',complete:function(){jQuery('#mobile-menu').navgoco({accordion:true});jQuery("#main-nav i").click(function(){jQuery("#mobile-menu").slideToggle("slow");});jQuery('#secondary-mobile-menu').navgoco({accordion:true});jQuery("#secondary-nav .secondary-mobile-label").click(function(){jQuery("#secondary-mobile-menu").slideToggle("slow");});}}]);if(jQuery('.geo-fullwidth-carousel').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/owl.carousel.js',complete:function(){jQuery('.geo-fullwidth-carousel').each(function(){var $this=jQuery(this),auto=parseInt($this.data('autoplay')),useNavigation=$this.data('navigation'),usePagination=$this.data('pagination');if('0'==auto){auto=false;}
useNavigation=('1'==useNavigation)?true:false;usePagination=('1'==usePagination)?true:false;$this.owlCarousel({singleItem:true,stopOnHover:true,lazyLoad:true,navigation:useNavigation,pagination:usePagination,navigationText:false,autoPlay:auto,paginationSpeed:parseInt($this.data('paginationspeed')),rewindSpeed:parseInt($this.data('rewindspeed'))});});}}]);};if(jQuery('.geo-hotnews-carousel-shows').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/owl.carousel.js',complete:function(){jQuery('.geo-hotnews-carousel-shows').each(function(){var $this=jQuery(this),auto=$this.data('autoplay');if('0'==auto){auto=false;}
$this.owlCarousel({items:parseInt($this.data('columns')),autoPlay:auto,slideSpeed:parseInt($this.data('paginationspeed')),paginationSpeed:parseInt($this.data('paginationspeed')),rewindSpeed:parseInt($this.data('rewindspeed')),itemsDesktop:[979,3],itemsDesktopSmall:[799,2],itemsTablet:[639,1],lazyLoad:true,navigation:true,pagination:false,navigationText:false,addClassActive:true,afterAction:function(){jQuery(".first-item-0").removeClass("first-item-0");jQuery(".geo-hotnews-carousel").find(".active").eq(0).addClass("first-item-0");}});});}}]);};if(jQuery('.geo-daily-carousel').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/owl.carousel.js',complete:function(){jQuery('.geo-daily-carousel').owlCarousel({singleItem:true,autoHeight:true,lazyLoad:true,navigation:true,pagination:false,navigationText:false});}}]);};if(jQuery('.geo-carousel-1').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/owl.carousel.js',complete:function(){jQuery('.geo-carousel-1').each(function(){var $this=jQuery(this),auto=$this.data('autoplay');if('0'==auto){auto=false;}
$this.owlCarousel({singleItem:true,lazyLoad:true,navigation:true,pagination:false,navigationText:false,autoPlay:auto,slideSpeed:parseInt($this.data('paginationspeed')),paginationSpeed:parseInt($this.data('paginationspeed')),rewindSpeed:parseInt($this.data('rewindspeed')),});});}}]);};if(jQuery('.geo-carousel-2').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/owl.carousel.js',complete:function(){jQuery('.geo-carousel-2').owlCarousel({items:3,itemsDesktop:[1024,3],itemsDesktopSmall:[979,3],itemsTablet:[799,3],lazyLoad:true,navigation:true,pagination:false,navigationText:false,addClassActive:true,afterAction:function(){jQuery(".center-item").removeClass("center-item");jQuery(".geo-carousel-2").find(".active").eq(1).addClass("center-item");}});}}]);};if(jQuery('.geo-single-post-carousel').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/owl.carousel.js',complete:function(){jQuery('.geo-single-post-carousel').owlCarousel({singleItem:true,stopOnHover:true,lazyLoad:true,navigation:true,pagination:false,navigationText:false,autoPlay:true});}}]);};if(jQuery('.geo-flex-1-widget').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/jquery.flexslider-min.js',complete:function(){jQuery('.geo-flex-wrapper').each(function(){var $this=jQuery(this),$main=$this.find('.geo-flexslider-1'),$thumbs=$this.find('.geo-flex-carousel-1');$thumbs.flexslider({animation:"slide",controlNav:false,directionNav:false,animationLoop:true,slideshow:true,animationDuration:400,slideshowSpeed:7000,itemWidth:90,itemMargin:0,asNavFor:'#'+ $main.attr('id')});$main.flexslider({animation:"slide",controlNav:false,directionNav:false,animationLoop:true,slideshow:true,animationDuration:400,slideshowSpeed:7000,prevText:"",nextText:"",sync:'#'+ $thumbs.attr('id'),start:function(slider){jQuery('body').removeClass('loading');}});});}}]);};if(jQuery('.geo-flex-2-widget').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/jquery.flexslider-min.js',complete:function(){jQuery('.geo-flexslider-2').each(function(){var $this=jQuery(this),auto=false;if('1'==$this.data('autoplay')){auto=true;}
$this.flexslider({animation:$this.data('animation'),controlNav:true,directionNav:false,animationLoop:false,slideshow:auto,slideshowSpeed:$this.data('autoplay-speed'),animationSpeed:$this.data('pagination-speed'),prevText:"",nextText:"",start:function(slider){slider.removeClass('loading');},after:function(slider){slider.find('.flex-caption').animate({bottom:0},400)},before:function(slider){jQuery('.geo-flexslider-2 .flex-caption').animate({bottom:-105},400)}});});}}]);};if(jQuery('.ei-slider').length>0){Modernizr.load([{load:geo_params.theme_uri+'js/jquery.eislideshow.js',complete:function(){jQuery('.ei-slider').each(function(){var $this=jQuery(this),auto=false;if('1'==$this.data('autoplay')){auto=true;}
$this.eislideshow({animation:$this.data('animation'),autoplay:auto,slideshow_interval:parseInt($this.data('auto-speed')),speed:parseInt($this.data('pagination-speed')),titlesFactor:0});});}}]);};if(jQuery(".video-wrapper").length>0){Modernizr.load([{load:geo_params.theme_uri+'js/fitvids.js',complete:function(){jQuery(".video-wrapper").fitVids();}}]);};if(jQuery('.contact-form').length>0){Modernizr.load([{load:[geo_params.theme_uri+'js/jquery.form.js',geo_params.theme_uri+'js/jquery.validate.js'],complete:function(){jQuery('.contact-form').validate({rules:{name:{required:true,minlength:2},email:{required:true,email:true},message:{required:true,minlength:10}},messages:{name:{required:geo_variable.i18n.validate.name.REQUIRED,minlength:jQuery.format(geo_variable.i18n.validate.name.MINLENGTH)},email:{required:geo_variable.i18n.validate.email.REQUIRED,email:geo_variable.i18n.validate.email.EMAIL},message:{required:geo_variable.i18n.validate.message.REQUIRED,minlength:jQuery.format(geo_variable.i18n.validate.message.MINLENGTH)}},submitHandler:function(form){jQuery(".contact-form .input-submit").attr("value",geo_variable.i18n.validate.form.SENDING);jQuery(form).ajaxSubmit({success:function(responseText,statusText,xhr,$form){jQuery("#response").html(responseText).hide().slideDown("fast");jQuery(".contact-form .input-submit").attr("value",geo_variable.i18n.validate.form.SUBMIT);}});return false;}});}}]);}
var map;if(jQuery('.geo-map').length>0){var id_map=jQuery('.geo-map').attr('id');var lat=parseFloat(jQuery('.geo-map').attr('data-latitude'));var lng=parseFloat(jQuery('.geo-map').attr('data-longitude'));var place=jQuery('.geo-map').attr('data-place');map=new GMaps({el:'#'+id_map,lat:lat,lng:lng,zoomControl:true,zoomControlOpt:{style:'SMALL',position:'TOP_LEFT'},panControl:false,streetViewControl:false,mapTypeControl:false,overviewMapControl:false});map.addMarker({lat:lat,lng:lng,title:place});};if(jQuery('#sb-search').length>0){Modernizr.load([{load:[geo_params.theme_uri+'js/uisearch.js',geo_params.theme_uri+'js/classie.js'],complete:function(){new UISearch(document.getElementById('sb-search'));}}]);};if(jQuery('.geo-flickr-widget-aaaa').length>0){Modernizr.load([{load:[geo_params.theme_uri+'js/jflickrfeed.js',geo_params.theme_uri+'js/imgliquid.js'],complete:function(){jQuery('.geo-flickr-widget ul').each(function(){var $this=jQuery(this),$wrap=$this.parent('.flickr-wrap');$this.jflickrfeed({limit:parseInt($wrap.data('limit')),qstrings:{id:$wrap.data('id')},itemTemplate:'<li class="flickr-badge-image">'+'<a target="blank" href="{{link}}" title="{{title}}" class="imgLiquid">'+'<img src="{{image_m}}" alt="{{title}}"  />'+'</a>'+'</li>'},function(data){jQuery('.geo-flickr-widget .imgLiquid').imgLiquid();});});}}]);}
jQuery(document).ready(function(){jQuery("#back-top").hide();jQuery(function(){jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>200){jQuery('#back-top').fadeIn();}else{jQuery('#back-top').fadeOut();}});jQuery('#back-top a').click(function(){jQuery('body,html').animate({scrollTop:0},800);return false;});});var acc_wrapper=jQuery('.acc-wrapper');if(acc_wrapper.length>0)
{jQuery('.acc-wrapper .accordion-container').hide();jQuery.each(acc_wrapper,function(index,item){jQuery(this).find(jQuery('.accordion-title')).first().addClass('active').next().show();});jQuery('.accordion-title').on('click',function(e){geo_accordion_click(jQuery(this));e.preventDefault();});var titles=jQuery('.accordion-title');jQuery.each(titles,function(){geo_accordion_click(jQuery(this));});}
function geo_accordion_click(obj){if(obj.next().is(':hidden')){obj.parent().find(jQuery('.active')).removeClass('active').next().slideUp(300);obj.toggleClass('active').next().slideDown(300);}
jQuery('.accordion-title span').removeClass('fa-chevron-up').addClass('fa-chevron-down');if(obj.hasClass('active')){obj.find('span').removeClass('fa-chevron-down');obj.find('span').addClass('fa-chevron-up');}}
jQuery('.toggle-view li').click(function(event){var text=jQuery(this).children('.geo-panel');if(text.is(':hidden')){jQuery(this).addClass('active');text.slideDown('300');jQuery(this).children('span').removeClass('fa-chevron-down');jQuery(this).children('span').addClass('fa-chevron-up');}else{jQuery(this).removeClass('active');text.slideUp('300');jQuery(this).children('span').removeClass('fa-chevron-up');jQuery(this).children('span').addClass('fa-chevron-down');}});});if(jQuery('#header-middle').hasClass('sticky')){Modernizr.load([{load:[geo_params.theme_uri+'js/waypoints.js',geo_params.theme_uri+'js/waypoints-sticky.js'],complete:function(){jQuery('#header-middle').waypoint('sticky');}}]);}
function get_search_post()
{var search_text=jQuery("#search").val();jQuery(document).click(function(){jQuery("#search_results_div").html('');jQuery("#search_results_div").css('display','none');jQuery("#sb-search").css('overflow','hidden');});jQuery(".text_search_block").click(function(event){event.stopPropagation();});if(search_text.length==0)
{jQuery("#search_results_div").html('');jQuery("#search_results_div").css('display','none');jQuery("#sb-search").css('overflow','hidden');}
else if(search_text.length>3)
{jQuery('.search_loader').css('display','inline');jQuery.ajax({type:'POST',url:BaseURL+'frontend/search/ajax_search/',data:'search_text='+search_text,cache:false,success:function(response){response=unescape(response);jQuery('.search_loader').css('display','none');if(response!='')
{jQuery("#sb-search").css('overflow','visible');jQuery("#search_results_div").css('display','block');jQuery("#search_results_div").html(response);}}});}}
function submit_search()
{var action_link=jQuery('#search_frm').attr('action');var search_text=jQuery('#search').val().toLowerCase();var search_text_link=search_text.replace(/ /g,"-");search_text_link=search_text_link.replace(/[^a-zA-Z0-9\-\\+\.]/g,"");search_text_link=search_text_link.replace(/\-{2,}/g,"-");if(search_text!=''){var action_link=action_link+search_text_link;window.location=action_link;}}
if(typeof(jQuery('#startDate').val())!="undefined"&&jQuery('#startDate').val()!==null){jQuery("#startDate").datepicker({dateFormat:'yy-mm-dd',maxDate:0});}
if(typeof(jQuery('#endDate').val())!="undefined"&&jQuery('#endDate').val()!==null){jQuery("#endDate").datepicker({dateFormat:'yy-mm-dd',maxDate:0});}
jQuery(document).ready(function(){setTimeout(nativeAdsRemove,1500);});function nativeAdsRemove()
{if(typeof(jQuery('.featured_native_top').val())!="undefined"&&jQuery('.featured_native_top').val()!==null)
{if(jQuery('#geo_widget_post_carousel-2 .top-story-owl-wrapper .featured_native_top').css('display')=='block')
{jQuery('#geo_widget_post_carousel-2 .top-story-owl-wrapper .top-story-owl-item:last-child').remove();}}}